backend:
  name: git-gateway
  branch: main
  identity_url: https://felizcumplepapi.netlify.app/.netlify/identity

media_folder: "assets/images" # Carpeta para subir imágenes
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
